# Define persistent storage for Prometheus (PVC)
prometheus:
  server:
    persistentVolume:
      enabled: true
  prometheusSpec:
    storageSpec:
      volumeClaimTemplate:
        spec:
          accessModes: ["ReadWriteOnce"]
          storageClassName: ssd-promethus
          resources:
            requests:
              storage: 5Gi

# Define persistent storage for Grafana (PVC)
grafana:
  # Set password for Grafana admin user
  #adminPassword: your_admin_password
  persistence:
    type: pvc
    enabled: true
    # annotations: {}
    finalizers:
      - kubernetes.io/pvc-protection
    existingClaim: pvc-claim-grafana
  plugins:
  - digrich-bubblechart-panel
  enabled: true
  env:
    GF_RENDERING_SERVER_URL: http://grafana-image-renderer:8081/render
    GF_RENDERING_CALLBACK_URL: http://my-prometheus-grafana:80/
    GF_LOG_FILTERS: rendering:debug
  grafana.ini:
    smtp:
      enabled: true
      host: "smtp.gmail.com:587"
      user: "name@gmail.com"
      password: "passwd**"
      skip_verify: true
      from_address: admin@grafana.com
      from_name: Grafana

# Define persistent storage for Alertmanager (PVC)
alertmanager:
  alertmanagerSpec:
    storage:
      volumeClaimTemplate:
        spec:
          accessModes: ["ReadWriteOnce"]
          storageClassName: ssd-promethus
          resources:
            requests:
              storage: 5Gi
