kind: PersistentVolume
apiVersion: v1
metadata:
  name: task-pv
  labels:
    type: amazonEBS
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
 #persistentVolumeReclaimPolicy: Recycle
 # persistentVolumeReclaimPolicy: Retain
  awsElasticBlockStore:
    volumeID: vol-036eb413a  #EBS Voulme ID
    fsType: ext4
