apiVersion: v1 
kind: LimitRange 
metadata: 
  name: jenkins-agent-limit-range 
  namespace: jenkins 
spec: 
  limits: 
    - type: Pod 
        max: 
          cpu: 2 
          memory: 4Gi 
        min: 
          cpu: 0.25 
          memory: 500Mi 
