apiVersion: v1
kind: Service
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"v1","kind":"Service","metadata":{"annotations":{},"labels":{"app.kubernetes.io/component":"server","app.kubernete                               s.io/name":"argocd-server","app.kubernetes.io/part-of":"argocd"},"name":"argocd-server","namespace":"argocd"},"spec":{"ports":[{"name"                               :"http","port":80,"protocol":"TCP","targetPort":8080},{"name":"https","port":443,"protocol":"TCP","targetPort":8080}],"selector":{"app                               .kubernetes.io/name":"argocd-server"}}}
  creationTimestamp: "2021-08-11T16:05:43Z"
  finalizers:
  - service.kubernetes.io/load-balancer-cleanup
  labels:
    app.kubernetes.io/component: server
    app.kubernetes.io/name: argocd-server
    app.kubernetes.io/part-of: argocd
  name: argocd-server
  namespace: argocd
  resourceVersion: "16362741"
  selfLink: /api/v1/namespaces/argocd/services/argocd-server
  uid: 0dff4e46-eceb-494b-a292-1b7ba4cddf07
spec:
  clusterIP: 10.4.124.230
  externalTrafficPolicy: Cluster
  ports:
  - name: http
    nodePort: 30569
    port: 80
    protocol: TCP
    targetPort: 8080
  - name: https
    nodePort: 30081
    port: 443
    protocol: TCP
    targetPort: 8080
  selector:
    app.kubernetes.io/name: argocd-server
  sessionAffinity: None
  type: LoadBalancer
status:
  loadBalancer:
    ingress:
    - hostname: a0dff4e46eceb494ba2921b7ba4cddf0-1013900206.us-east-1.elb.amazonaws.com
