kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: pvc-claim
  labels:
    types: amazonEBS
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: storage-class-jenkins
