apiVersion: v1
kind: PersistentVolume
metadata:
  name: efs-pv
spec:
  capacity:
    storage: 5Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: efs-csi
  csi:
    driver: efs.csi.aws.com
    volumeHandle: fs-0a6606be:/efsbibin-subpath:fsap-07449b8e6e87b9f3e


# create the subpath under the access point path eg: /images
#It is possible to use a combination of volume path and access points with a volumeHandle of the form [FileSystemId]:[Subpath]:[AccessPointId], e.g. volumeHandle: fs-e8a95a42:/my/subpath:fsap-19f752f0068c22464. In this case:
#The [Subpath] will be under the configured access point directory. For example, if you configured your access point with /ap1, the above would mount to /ap1/my/subpath.
#As with normal volume path, the [Subpath] must already exist prior to consuming the volume from a pod.
#https://github.com/kubernetes-sigs/aws-efs-csi-driver/blob/master/examples/kubernetes/access_points/README.md
 
 #Only the access point id
 #volumeHandle: fs-0a6606be::fsap-07449b8e6e87b9f3e

