apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: task-pvc
  labels:
    app: ngnix
spec:
  storageClassName: task-aws-sc
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
