apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: task-aws-sc
provisioner: kubernetes.io/aws-ebs
parameters:
  type: gp2
  # zones: eu-east-1a, eu-east-1b
  iopsPerGB: "10"
  fsType: ext4
reclaimPolicy: Retain
allowVolumeExpansion: true
mountOptions:
  - debug
volumeBindingMode: Immediate
