apiVersion: v1
kind: Service
metadata:
  name: jenkins5000
  labels:
    app: jenkins5000
spec:
  type: ClusterIP
  ports:
    - name: slave
      port: 50000
      protocol: TCP
    - name: http
      port: 80
      targetPort: 8080
  selector:
    app: jenkins
