kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: pvc-claim-prometheus
  labels:
    types: amazonEBS
  namespace: monitoring
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: ssd-prometheus
